# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: ^{{cookiecutter.repo_name}}

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # [Keep all these as they serve different purposes than linting]
      - id: check-merge-conflict
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-symlinks
      - id: check-added-large-files
        args: ["--maxkb=500"]
        exclude: |
          (?x)(
              ^example/large/file.csv|
              ^example/large/sklearn-model.pkl
          )
      - id: requirements-txt-fixer
      - id: forbid-new-submodules
      - id: detect-private-key

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.261" # Update to latest version
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --config=./pyproject.toml]

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args:
          - --config=./pyproject.toml

  - repo: https://github.com/PyCQA/pylint
    rev: v2.16.3
    hooks:
      - id: pylint
        args:
          - --rcfile=./pyproject.toml
